volumes:
  postgres_data:
    driver: local

services:

  db:
    image: postgres:14
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 100
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      PGUSER: postgres
    ports:
      - "5432:5432"

  validation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: validation
    entrypoint: [ "/app/service" ]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
